import crypto from 'node:crypto';
import type { ConversationMessageRow, ConversationThreadRow } from '../state/conversationStore.js';

/**
 * One renderer, two consumers: the GitHub publisher (durable repo files,
 * channel indexes, DECISIONS.md) and the `@miniOG handoff` command
 * (paste-ready bundle for the user's own Claude). Keeping them on the same
 * renderer means the knowledge base and the handoff never drift.
 */

const TRANSCRIPT_MESSAGE_CLIP_CHARS = 500;
const HANDOFF_TRANSCRIPT_MAX_MESSAGES = 60;

export function contentHash(text: string): string {
  return crypto.createHash('sha256').update(text, 'utf8').digest('hex');
}

/** Filesystem/URL-safe kebab slug. */
export function slugify(text: string, maxChars = 48): string {
  const slug = text
    .toLowerCase()
    .replace(/<@[^>]+>/g, ' ')
    .replace(/[^\p{L}\p{N}]+/gu, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, maxChars)
    .replace(/-+$/g, '');
  return slug || 'thread';
}

/**
 * Repo-relative file path for a thread. Assigned ONCE at first publish and
 * then reused from egress_exports.target_path — the slug is derived from the
 * title, which can change across re-synthesis, and the path must not.
 */
export function threadFilePath(thread: ConversationThreadRow): string {
  const channel = slugify(thread.channelName ?? thread.channelId, 40);
  const anchorTs = Number(thread.firstMessageTs ?? thread.threadTs);
  const month =
    Number.isFinite(anchorTs) && anchorTs > 0 ? new Date(anchorTs * 1000).toISOString().slice(0, 7) : 'unknown';
  const tsSafe = thread.threadTs.replace(/\./g, '-');
  return `threads/${channel}/${month}/${tsSafe}-${slugify(thread.title ?? 'thread')}.md`;
}

function tsToDate(ts?: string): string {
  const value = Number(ts);
  if (!Number.isFinite(value) || value <= 0) return '';
  return new Date(value * 1000).toISOString().slice(0, 10);
}

function tsToDateTime(ts?: string): string {
  const value = Number(ts);
  if (!Number.isFinite(value) || value <= 0) return '';
  return new Date(value * 1000).toISOString().slice(0, 16).replace('T', ' ');
}

function speaker(message: ConversationMessageRow): string {
  if (message.isBot) return 'miniOG';
  return message.displayName ?? message.userId ?? 'unknown';
}

function humanParticipants(thread: ConversationThreadRow): string {
  return thread.participants
    .filter(p => !p.isBot)
    .map(p => p.displayName ?? p.userId)
    .join(', ');
}

function transcriptLines(messages: ConversationMessageRow[], maxMessages: number): string[] {
  return messages
    .filter(m => m.text.trim())
    .slice(-maxMessages)
    .map(m => {
      const text =
        m.text.length > TRANSCRIPT_MESSAGE_CLIP_CHARS ? `${m.text.slice(0, TRANSCRIPT_MESSAGE_CLIP_CHARS)}…` : m.text;
      return `- **[${tsToDateTime(m.messageTs)}] ${speaker(m)}:** ${text.replace(/\n/g, '\n  ')}`;
    });
}

export interface RenderThreadOptions {
  includeTranscript: boolean;
  /** Slack permalink to the thread root, when resolvable. */
  slackPermalink?: string;
}

/** The durable per-thread markdown file for the GitHub knowledge repo. */
export function renderThreadMarkdown(
  thread: ConversationThreadRow,
  messages: ConversationMessageRow[],
  opts: RenderThreadOptions,
): string {
  const lines: string[] = [];
  lines.push(`# ${thread.title ?? 'Slack thread'}`);
  lines.push('');
  lines.push('> Auto-generated by miniOG from a Slack conversation. Edits here are overwritten on the next sync —');
  lines.push('> continue the discussion in the Slack thread instead.');
  lines.push('');
  lines.push(`- **Channel:** ${thread.channelName ? `#${thread.channelName}` : thread.channelId}`);
  const first = tsToDate(thread.firstMessageTs);
  const last = tsToDate(thread.lastActivityTs);
  lines.push(`- **When:** ${first}${last && last !== first ? ` → ${last}` : ''}`);
  const people = humanParticipants(thread);
  if (people) lines.push(`- **Participants:** ${people}`);
  lines.push(
    `- **Slack thread:** ${opts.slackPermalink ?? `channel \`${thread.channelId}\`, thread \`${thread.threadTs}\``}`,
  );
  lines.push('');
  lines.push('## TL;DR');
  lines.push('');
  lines.push(thread.summary || '_Not yet summarized._');
  if (thread.decisions.length > 0) {
    lines.push('');
    lines.push('## Decisions');
    lines.push('');
    for (const decision of thread.decisions) lines.push(`- ${decision}`);
  }
  if (thread.actionItems.length > 0) {
    lines.push('');
    lines.push('## Action items');
    lines.push('');
    for (const item of thread.actionItems) lines.push(`- ${item}`);
  }
  if (opts.includeTranscript) {
    const transcript = transcriptLines(messages, Number.MAX_SAFE_INTEGER);
    if (transcript.length > 0) {
      lines.push('');
      lines.push('## Transcript');
      lines.push('');
      lines.push(...transcript);
    }
  }
  lines.push('');
  return lines.join('\n');
}

export interface HandoffOptions {
  slackPermalink?: string;
  /** GitHub URL of the published file, when it exists. */
  githubUrl?: string;
}

/**
 * Paste-ready context bundle for "continue this in your own Claude". Unlike
 * the repo file, the condensed transcript is ALWAYS included — the recipient
 * chose to export a thread they can already read in Slack.
 */
export function renderHandoffBundle(
  thread: ConversationThreadRow,
  messages: ConversationMessageRow[],
  opts: HandoffOptions = {},
): string {
  const lines: string[] = [];
  lines.push(`# Continuing a Slack discussion: ${thread.title ?? 'Slack thread'}`);
  lines.push('');
  const channel = thread.channelName ? `#${thread.channelName}` : thread.channelId;
  const people = humanParticipants(thread);
  lines.push(
    `> Context handoff generated by miniOG. Source: ${opts.slackPermalink ?? `Slack ${channel}, thread ${thread.threadTs}`}` +
      `${people ? ` · Participants: ${people}` : ''}${opts.githubUrl ? ` · Knowledge base: ${opts.githubUrl}` : ''}`,
  );
  lines.push('');
  lines.push('## Where we are (TL;DR)');
  lines.push('');
  lines.push(thread.summary || '_No synthesis yet — the transcript below is the context._');
  if (thread.decisions.length > 0) {
    lines.push('');
    lines.push('## Decisions made');
    lines.push('');
    for (const decision of thread.decisions) lines.push(`- ${decision}`);
  }
  if (thread.actionItems.length > 0) {
    lines.push('');
    lines.push('## Open action items');
    lines.push('');
    for (const item of thread.actionItems) lines.push(`- ${item}`);
  }
  const transcript = transcriptLines(messages, HANDOFF_TRANSCRIPT_MAX_MESSAGES);
  if (transcript.length > 0) {
    lines.push('');
    lines.push('## Transcript (condensed, oldest first)');
    lines.push('');
    lines.push(...transcript);
  }
  lines.push('');
  lines.push('## Suggested next prompt');
  lines.push('');
  lines.push('"Given the Slack context above, help me continue this work: <what you want to do next>"');
  lines.push('');
  return lines.join('\n');
}

export interface IndexEntry {
  title: string;
  date: string;
  summary?: string;
  /** Path of the thread file RELATIVE to the README's own directory. */
  relPath: string;
}

/** Per-channel README.md listing every published thread, newest first. */
export function renderChannelIndex(channelLabel: string, entries: IndexEntry[]): string {
  const lines: string[] = [];
  lines.push(`# ${channelLabel} — miniOG conversations`);
  lines.push('');
  lines.push('> Auto-generated index. One file per Slack thread miniOG took part in.');
  lines.push('');
  // Deterministic order (date desc, then title) so re-renders of unchanged
  // data never produce line-shuffle diffs and noise commits.
  const sorted = [...entries].sort((a, b) =>
    a.date === b.date ? a.title.localeCompare(b.title) : a.date < b.date ? 1 : -1,
  );
  for (const entry of sorted) {
    const summary = entry.summary ? ` — ${entry.summary.replace(/\n/g, ' ').slice(0, 160)}` : '';
    lines.push(`- ${entry.date} · [${entry.title}](./${encodeURI(entry.relPath)})${summary}`);
  }
  lines.push('');
  return lines.join('\n');
}

export interface DecisionEntry {
  decision: string;
  threadTitle: string;
  date: string;
  /** Repo-relative path of the thread file. */
  path: string;
}

/** Rolling top-level DECISIONS.md — the highest-value grep target. */
export function renderDecisionsIndex(entries: DecisionEntry[]): string {
  const lines: string[] = [];
  lines.push('# Decisions');
  lines.push('');
  lines.push('> Auto-generated by miniOG: every decision extracted from captured Slack threads, newest first.');
  lines.push('> Treat as a pointer back to the source thread, not as an authority on its own.');
  lines.push('');
  // Same determinism rule as the channel index: stable order, no noise diffs.
  const sorted = [...entries].sort((a, b) =>
    a.date === b.date ? a.decision.localeCompare(b.decision) : a.date < b.date ? 1 : -1,
  );
  for (const entry of sorted) {
    lines.push(`- **${entry.date}** — ${entry.decision} _([${entry.threadTitle}](./${encodeURI(entry.path)}))_`);
  }
  lines.push('');
  return lines.join('\n');
}
