import { describe, expect, it } from 'vitest';
import {
  contentHash,
  renderChannelIndex,
  renderDecisionsIndex,
  renderHandoffBundle,
  renderThreadMarkdown,
  slugify,
  threadFilePath,
} from '../src/egress/threadMarkdownRenderer.js';
import type { ConversationMessageRow, ConversationThreadRow } from '../src/state/conversationStore.js';

// Pure renderers — no quiet-window/now gates — so fixed epochs give deterministic date assertions.
const AUG1 = '1754006400.000100'; // 2025-08-01T00:00:00Z
const AUG3 = '1754179200.000500'; // 2025-08-03T00:00:00Z
const JUN27 = '1751000000.000200'; // 2025-06-27 — differs from AUG1's month on purpose
const PERMALINK = 'https://example.slack.com/archives/C123/p1754006400000100';

function threadRow(overrides: Partial<ConversationThreadRow> = {}): ConversationThreadRow {
  return {
    id: 1,
    channelId: 'C123',
    threadTs: AUG1,
    channelName: 'eng-deploys',
    channelType: 'channel',
    visibility: 'org',
    status: 'active',
    title: 'Deploy failure RCA',
    summary: 'Staging deploy failed because of a bad env var.',
    decisions: [],
    actionItems: [],
    participants: [
      { userId: 'UALICE', displayName: 'alice', isBot: false, messageCount: 3 },
      { userId: 'UBOB', isBot: false, messageCount: 1 },
      { userId: 'UBOT', displayName: 'miniOG', isBot: true, messageCount: 2 },
    ],
    messageCount: 6,
    firstMessageTs: AUG1,
    lastActivityTs: AUG3,
    synthesizedMessageCount: 0,
    createdAt: '2025-08-01T00:00:00.000Z',
    updatedAt: '2025-08-03T00:00:00.000Z',
    ...overrides,
  };
}

function messageRow(messageTs: string, overrides: Partial<ConversationMessageRow> = {}): ConversationMessageRow {
  return {
    id: 1,
    threadId: 1,
    channelId: 'C123',
    threadTs: AUG1,
    messageTs,
    userId: 'UALICE',
    displayName: 'alice',
    isBot: false,
    text: 'hello there',
    files: [],
    edited: false,
    capturedAt: '2025-08-01T00:00:00.000Z',
    ...overrides,
  };
}

function transcriptBullets(markdown: string): string[] {
  return markdown.split('\n').filter(line => line.startsWith('- **['));
}

describe('slugify', () => {
  it('lowercases and kebab-cases plain text', () => {
    expect(slugify('Hello World Foo')).toBe('hello-world-foo');
  });

  it('strips <@mentions> and punctuation while keeping unicode letters', () => {
    expect(slugify('ping <@U05EUC842KD> re: deploy!')).toBe('ping-re-deploy');
    expect(slugify('Grafana über café ☕ alerts')).toBe('grafana-über-café-alerts');
  });

  it('caps length and never leaves a trailing dash at the cut', () => {
    expect(slugify('a'.repeat(60))).toBe('a'.repeat(48));
    expect(slugify(`${'a'.repeat(47)} bbb`)).toBe('a'.repeat(47));
    expect(slugify('one two three', 7)).toBe('one-two');
  });

  it("falls back to 'thread' when nothing survives", () => {
    expect(slugify('')).toBe('thread');
    expect(slugify('!!! ???')).toBe('thread');
    expect(slugify('<@U1> <@U2>')).toBe('thread');
  });
});

describe('threadFilePath', () => {
  it('builds threads/<channel-slug>/<YYYY-MM>/<ts-with-dashes>-<title-slug>.md with month from firstMessageTs', () => {
    const row = threadRow({
      channelName: 'Eng Deploys',
      threadTs: JUN27,
      firstMessageTs: AUG1,
      title: 'Deploy Failed: Staging!',
    });
    // Month comes from firstMessageTs (2025-08), not threadTs (2025-06); dots in ts become dashes.
    expect(threadFilePath(row)).toBe('threads/eng-deploys/2025-08/1751000000-000200-deploy-failed-staging.md');
  });

  it('slugs the channelId when there is no channelName', () => {
    const row = threadRow({ channelName: undefined, channelId: 'C0123ABC' });
    expect(threadFilePath(row)).toBe(`threads/c0123abc/2025-08/${AUG1.replace('.', '-')}-deploy-failure-rca.md`);
  });

  it("uses the 'unknown' month bucket and the 'thread' title slug when nothing parses", () => {
    const row = threadRow({ channelName: 'ops', threadTs: 'garbage', firstMessageTs: undefined, title: undefined });
    expect(threadFilePath(row)).toBe('threads/ops/unknown/garbage-thread.md');
  });
});

describe('renderThreadMarkdown', () => {
  it('renders title, overwrite warning, metadata with human-only participants, and the permalink', () => {
    const row = threadRow({
      decisions: ['Rotate the staging env var'],
      actionItems: ['alice to add a deploy preflight check'],
    });
    const output = renderThreadMarkdown(row, [], { includeTranscript: false, slackPermalink: PERMALINK });

    expect(output.split('\n')[0]).toBe('# Deploy failure RCA');
    expect(output).toContain('> Auto-generated by miniOG from a Slack conversation. Edits here are overwritten');
    expect(output).toContain('- **Channel:** #eng-deploys');
    expect(output).toContain('- **When:** 2025-08-01 → 2025-08-03');
    expect(output).toContain('- **Participants:** alice, UBOB');
    expect(output).not.toContain('miniOG,');
    expect(output).toContain(`- **Slack thread:** ${PERMALINK}`);
    expect(output).toContain('## TL;DR\n\nStaging deploy failed because of a bad env var.');
    expect(output).toContain('## Decisions\n\n- Rotate the staging env var');
    expect(output).toContain('## Action items\n\n- alice to add a deploy preflight check');
    expect(output).not.toContain('## Transcript');
  });

  it('falls back to channel/thread refs, single date, TL;DR placeholder, and omits empty sections', () => {
    const row = threadRow({
      channelName: undefined,
      summary: undefined,
      participants: [{ userId: 'UBOT', displayName: 'miniOG', isBot: true, messageCount: 2 }],
      firstMessageTs: AUG1,
      lastActivityTs: '1754006460.000900', // same day → no range arrow
    });
    const output = renderThreadMarkdown(row, [], { includeTranscript: false });

    expect(output).toContain('- **Channel:** C123');
    expect(output).toContain('- **When:** 2025-08-01\n');
    expect(output).not.toContain('→');
    expect(output).not.toContain('- **Participants:**');
    expect(output).toContain(`- **Slack thread:** channel \`C123\`, thread \`${AUG1}\``);
    expect(output).toContain('## TL;DR\n\n_Not yet summarized._');
    expect(output).not.toContain('## Decisions');
    expect(output).not.toContain('## Action items');
  });

  it('renders the transcript only when includeTranscript, with speaker labels, clipping, and indentation', () => {
    const messages = [
      messageRow(AUG1, { text: 'first line\nsecond line' }),
      messageRow('1754006460.000200', { userId: 'UBOT', displayName: 'watchtower', isBot: true, text: 'bot reply' }),
      messageRow('1754006520.000300', { userId: 'UCHARLIE', displayName: undefined, text: 'plain' }),
      messageRow('1754006580.000400', { text: '   ' }),
      messageRow('1754006640.000500', { text: 'x'.repeat(600) }),
    ];
    const withTranscript = renderThreadMarkdown(threadRow(), messages, { includeTranscript: true });

    expect(withTranscript).toContain('## Transcript');
    expect(withTranscript).toContain('- **[2025-08-01 00:00] alice:** first line\n  second line');
    expect(withTranscript).toContain('- **[2025-08-01 00:01] miniOG:** bot reply');
    expect(withTranscript).toContain('- **[2025-08-01 00:02] UCHARLIE:** plain');
    expect(withTranscript).toContain(`${'x'.repeat(500)}…`);
    expect(withTranscript).not.toContain('x'.repeat(501));
    expect(transcriptBullets(withTranscript)).toHaveLength(4); // whitespace-only message filtered

    const withoutFlag = renderThreadMarkdown(threadRow(), messages, { includeTranscript: false });
    expect(withoutFlag).not.toContain('## Transcript');
  });

  it('omits the Transcript heading when every message is blank even with includeTranscript', () => {
    const output = renderThreadMarkdown(threadRow(), [messageRow(AUG1, { text: '  \n ' })], {
      includeTranscript: true,
    });
    expect(output).not.toContain('## Transcript');
  });
});

describe('renderHandoffBundle', () => {
  it('renders header, source line with permalink/github/participants, sections, and the prompt footer', () => {
    const row = threadRow({ decisions: ['Ship the fix behind a flag'], actionItems: ['bob to verify on staging'] });
    const output = renderHandoffBundle(row, [messageRow(AUG1, { text: 'kickoff' })], {
      slackPermalink: PERMALINK,
      githubUrl: 'https://github.com/org/kb/blob/main/threads/x.md',
    });

    expect(output.split('\n')[0]).toBe('# Continuing a Slack discussion: Deploy failure RCA');
    expect(output).toContain(`Source: ${PERMALINK}`);
    expect(output).toContain('· Participants: alice, UBOB');
    expect(output).toContain('· Knowledge base: https://github.com/org/kb/blob/main/threads/x.md');
    expect(output).toContain('## Where we are (TL;DR)\n\nStaging deploy failed because of a bad env var.');
    expect(output).toContain('## Decisions made\n\n- Ship the fix behind a flag');
    expect(output).toContain('## Open action items\n\n- bob to verify on staging');
    expect(output).toContain('## Transcript (condensed, oldest first)');
    expect(output).toContain('## Suggested next prompt');
    expect(output).toContain('"Given the Slack context above, help me continue this work: <what you want to do next>"');
  });

  it('falls back to a textual Slack source ref and the no-synthesis TL;DR, keeping the transcript', () => {
    const named = renderHandoffBundle(threadRow({ summary: '' }), [messageRow(AUG1, { text: 'kickoff' })]);
    expect(named).toContain(`Source: Slack #eng-deploys, thread ${AUG1}`);
    expect(named).toContain('_No synthesis yet — the transcript below is the context._');
    expect(named).toContain('## Transcript (condensed, oldest first)');
    expect(named).toContain('- **[2025-08-01 00:00] alice:** kickoff');

    const unnamed = renderHandoffBundle(threadRow({ channelName: undefined }), []);
    expect(unnamed).toContain(`Source: Slack C123, thread ${AUG1}`);
  });

  it('condenses the transcript to the last 60 messages', () => {
    const messages = Array.from({ length: 65 }, (_, i) => messageRow(`${1754006400 + i}.000100`, { text: `msg-${i}` }));
    const output = renderHandoffBundle(threadRow(), messages);
    const bullets = transcriptBullets(output);

    expect(bullets).toHaveLength(60);
    expect(bullets[0]).toContain('msg-5');
    expect(bullets[59]).toContain('msg-64');
    expect(output).not.toContain('msg-4\n'); // msg-45 etc. still contain 'msg-4', so anchor to end-of-line
    expect(output).not.toContain('msg-0');
  });
});

describe('renderChannelIndex', () => {
  it('lists entries newest-first with encoded links and single-line 160-char summaries', () => {
    const longSummary = `line one\n${'y'.repeat(200)}`;
    const output = renderChannelIndex('#eng-deploys', [
      { title: 'Old thread', date: '2025-06-10', relPath: '2025-06/old.md' },
      { title: 'Spaced thread', date: '2025-08-02', relPath: '2025-08/a b.md', summary: longSummary },
      { title: 'Mid thread', date: '2025-07-15', relPath: '2025-07/mid.md', summary: 'short' },
    ]);

    expect(output.split('\n')[0]).toBe('# #eng-deploys — miniOG conversations');
    expect(output).toContain('> Auto-generated index. One file per Slack thread miniOG took part in.');

    const aug = output.indexOf('- 2025-08-02');
    const jul = output.indexOf('- 2025-07-15');
    const jun = output.indexOf('- 2025-06-10');
    expect(aug).toBeGreaterThan(-1);
    expect(aug).toBeLessThan(jul);
    expect(jul).toBeLessThan(jun);

    expect(output).toContain('[Spaced thread](./2025-08/a%20b.md)');
    expect(output).toContain(` — line one ${'y'.repeat(151)}`); // newline flattened, clipped to 160 chars
    expect(output).not.toContain('y'.repeat(152));
    expect(output).toContain('- 2025-06-10 · [Old thread](./2025-06/old.md)\n'); // no summary → no dash suffix
  });
});

describe('renderDecisionsIndex', () => {
  it('renders the caveat header and newest-first decision lines linking back to their threads', () => {
    const output = renderDecisionsIndex([
      { decision: 'Adopt blue/green deploys', threadTitle: 'Deploy RCA', date: '2025-06-10', path: 'threads/a.md' },
      {
        decision: 'Freeze Friday releases',
        threadTitle: 'Release cadence',
        date: '2025-08-02',
        path: 'threads/b c.md',
      },
    ]);

    expect(output.split('\n')[0]).toBe('# Decisions');
    expect(output).toContain('> Auto-generated by miniOG: every decision extracted from captured Slack threads');
    expect(output).toContain('> Treat as a pointer back to the source thread, not as an authority on its own.');
    expect(output).toContain('- **2025-08-02** — Freeze Friday releases _([Release cadence](./threads/b%20c.md))_');
    expect(output).toContain('- **2025-06-10** — Adopt blue/green deploys _([Deploy RCA](./threads/a.md))_');
    expect(output.indexOf('2025-08-02')).toBeLessThan(output.indexOf('2025-06-10'));
  });
});

describe('contentHash', () => {
  it('is a stable sha256 hex for identical input and differs on any change', () => {
    const a = contentHash('same content');
    expect(a).toMatch(/^[0-9a-f]{64}$/);
    expect(contentHash('same content')).toBe(a);
    expect(contentHash('same content!')).not.toBe(a);
  });
});
